### PR TITLE
Event viewer

### LINKED ISSUE #29: Add an event viewer
**Is your feature request related to a problem? Please describe.**
I want to see the antenna pulses from fluence maps interactively

**Describe the solution you'd like**
An event viewer similar to the offline one.

### PR DESCRIPTION
**Pull request by psampathkumar**
Closes #29

### CODE REVIEW

**Comment by psampathkumar** [comment]
No, there isnt. What do you think the clear button should do ? I think its better we merge this unless something breaks badly and then create an issue for tweaks.

**Comment by jelenakhlr** [comment]
Well the clear button clearing anything is a bit weird to me because there's no option to load another fluence map (unless I am missing something). I think it should just clear the selected stations and traces. But that's really personal preference :)

**Comment by jelenakhlr** [comment]
But yes, since this works, we can merge now and create another issue for the clear button

**Comment by psampathkumar** [comment]
You click on the fluence name again to load it :)

**Pull request merged**
